### ISSUE TITLE
Wireless ISP programming

### ISSUE THREAD

**Issue by fitzsim** [bitbank2/SMART_bootloader#1]
This looks like a great bootloader, thank you for publishing it.

Can `wireless_uploader.ino` work in a mode where instead of receiving programming commands via serial, it receives them from an ISP programmer like the USBasp?  I normally use `make ispload` to upload sketches.

I've wired up my SMART Response XE to my USBasp via the internal ISP header, which was somewhat easy to do (after opening the case, which was hard), and I'm able to flash SMART_bootloader using `avrdude -c usbasp ...` (`make ISPTOOL=usbasp atmega128rfa1_isp`).

If possible, I'd like this hacked up unit to act as the programmer hub for other units, but without modifying it further to break out a serial cable.

**Comment by bitbank2** [comment]
If you're programming it with the ISP header then you don't need a bootloader. You're programming directly into the built-in functionality of the MCU. The ISP header can be used to program both bootloaders and "sketches" directly.

**Comment by fitzsim** [comment]
I only have the one hacked up unit so far, and yes I can program it (bootloaders and sketches) directly via the ISP header.

I'm buying more units though.  For those units, I'll program SMART_bootloader using the POGO headers but I'm not going to open the cases.

What I'm envisioning is:

`[ PC ] <- USBasp -> [ hacked up unit ] <- wireless -> [ unopened unit ]`

With `wireless_uploader.ino` running on the hacked up unit, will I be able to load sketches from the PC to the unopened unit using `make ispload`?  Or will I need to replace USBasp with a serial cable, break a serial connection out of the hacked up unit, and use "make upload" (serial upload mode) on the PC?

**Comment by bitbank2** [comment]
You won't be able to upload wirelessly to an unopened unit unless it's running my bootloader code. I haven't had any in my possession for a few years now, so I can't really say much more about it.
